### ISSUE TITLE
How to preview email templates

### ISSUE THREAD

**Issue by davevilela** [webtretech/nestjs-mailer-react-adapter#29]
Hey, nice package! I have successfully integrated this package into my project, but I'm wondering how would be the recommended workflow for previewing my templates with hot-reloading.

Thanks in advance ! :D

**Comment by kodjunkie** [comment]
@davevilela you can either use any third-party mail testing service 
Or set `preview: true` in the config to enable the built-in mail preview.

Your config options should look like this
```javascript
MailerModule.forRoot({
  transport: {
    host: "smtp.domain.com",
    secure: false,
    auth: {
      user: "user@domain.com",
      pass: "password",
    },
  },
  defaults: {
    from: '"From Name" <hello@domain.com>',
  },
  template: {
    dir: __dirname + '/templates',
    adapter: new ReactAdapter(),
  },
  preview: true,
})
```
