### ISSUE TITLE
Documentation improvements to be more clear

### ISSUE THREAD

**Issue by yangricardo** [webtretech/nestjs-mailer-react-adapter#39]
Hi, thanks a lot for the initiative of open sourcing this adapter, it has given me a direction on how integrate the React Email with NestJS.

But i had some issues on how setup this at first. 

Here some points i think the instructions should be improved. In my case i configured the templates directory at `src/emails/templates`, containing the `tsx` files with react email templates.

A base point i have done were to [setup swc builder](https://docs.nestjs.com/recipes/swc#monorepo) with `swc-loader` and updating the test rules with `test: /\.(tsx|ts|js|cjs|mjs)$/,` at `webpack.config.js`

```js
import { swcDefaultsFactory } from '@nestjs/cli/lib/compiler/defaults/swc-defaults';

const swcDefaultConfig = swcDefaultsFactory().swcOptions;

export const module = {
  rules: [
    {
      test: /\.(tsx|ts|js|cjs|mjs)$/,
      exclude: /node_modules/,
      use: {
        loader: 'swc-loader',
        options: swcDefaultConfig,
      },
    },
  ],
};
```
Also, i had to setup a `.swcrc` file, updating the sample with `tsx=true`

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "sourceMaps": true,  
  "module": {
    "type": "commonjs"
  },
  "jsc": {
    "target": "es2022",
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true,
      "tsx": true  
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true      
    },
    "keepClassNames": true,
  },
  "minify": true
}
```

Also, is important to have `jsx` set as `preserve`  on `tsconfig.json`.

Also, is import some scripts configured on `package.json` for the developmen of the templates.

> "emails:dev": "email dev --dir src/emails/templates --port 5000",
> "emails:export": "email export --dir src/emails/templates --outDir dist/emails/templates"

With this setup, is even not necessary run `yarn emails:export`, each time the server hot reloads on development mode, the templates are updated on `dist/emails/templates`.

By end, i had to do 2 updates on your adapter implementation:

![image](https://github.com/webtretech/nestjs-mailer-react-adapter/assets/5523565/b4997436-2481-433c-b6d8-b73b0846a60c)

1. With a console log, i noticed that this generic import were receiving a undefined, i updated from `tmpl.default.default` to `tmpl.default`
2. [Looking at the docs](https://react.email/docs/integrations/nodemailer), as this is a NodeJS backend project, i updated from JSX Tag notation to function call, to avoid some errors..

**Comment by kodjunkie** [comment]
Hi @yangricardo, you can give the latest release a try. Also, the documentation is fine and you don't need any extra setup.
