### ISSUE TITLE
Cannot find module '/Users/xxxx/node/nestjs-prisma-starter/dist/templates/welcome.js

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [webtretech/nestjs-mailer-react-adapter#46]
Something seems to have gone wrong with it. The system doesn't seem to be generating welcomm.js automatically.
Also, if you don't import react.    welcome.tsx will throw an error.

![image](https://github.com/webtretech/nestjs-mailer-react-adapter/assets/5756752/2ebb585d-6a73-4696-a573-30a2451c4d1a)
<img width="405" alt="image" src="https://github.com/webtretech/nestjs-mailer-react-adapter/assets/5756752/59bc167b-d56a-424d-a035-1370f8ab7442">
![image](https://github.com/webtretech/nestjs-mailer-react-adapter/assets/5756752/fde44ba7-9ba0-4fb6-8faa-ef7be256f0a2)

**Comment by Darkhorse-Fraternity** [comment]
![image](https://github.com/webtretech/nestjs-mailer-react-adapter/assets/5756752/b8457759-18d0-41ae-9285-71db418c8eff)

**Comment by kodjunkie** [comment]
Hi @Darkhorse-Fraternity! 
The sample in the readme works. Are you using a different build setup? Or if you could create a demo repo with this issue, then I can take a look.

**Comment by essuraj** [comment]
i have libraries projects in nest.js and that outputs all the code inside 1 file ie... dist/main.js
in this case only d.ts files are being generated with folder structure.. so all the js files are missing.. and i get the above issue
